### ISSUE TITLE
unable to open jupyter notebook

### ISSUE THREAD

**Issue by neeti306** [rabobank-cdc/DeTTECT#103]
Traceback (most recent call last):
File "C:\ProgramData\anaconda3\Lib\site-packages\notebook\traittypes.py", line 235, in _resolve_classes
klass = self._resolve_string(klass)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 2020, in _resolve_string
return import_item(string)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\traitlets\utils\importstring.py", line 31, in import_item
module = __import__(package, fromlist=[obj])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "C:\ProgramData\anaconda3\Scripts\jupyter-notebook.exe\__main__.py", line 7, in 
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\jupyter_core\application.py", line 282, in launch_instance
super().launch_instance(argv=argv, **kwargs)
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1044, in launch_instance
app = cls.instance(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\traitlets\config\configurable.py", line 556, in instance
inst = cls(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1306, in __new__
inst.setup_instance(*args, **kwargs)
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1349, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "C:\Users\vinay\AppData\Roaming\Python\Python311\site-packages\traitlets\traitlets.py", line 1325, in setup_instance
init(self)
File "C:\ProgramData\anaconda3\Lib\site-packages\notebook\traittypes.py", line 226, in instance_init
self._resolve_classes()
File "C:\ProgramData\anaconda3\Lib\site-packages\notebook\traittypes.py", line 238, in _resolve_classes
warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'

**Comment by rubinatorz** [comment]
Hi @neeti306 

I'm not getting the picture. Within DeTT&CT we don't have nor use Jupyter notebooks. Can you share some more context on what you are trying to accomplish?

Regards
Ruben

**Comment by neeti306** [comment]
![2023-09-29](https://github.com/rabobank-cdc/DeTTECT/assets/146351014/d16956d7-2596-44ec-ad89-1dd5e586daa7)

**Comment by rubinatorz** [comment]
Which notebook? Because we don't have Jupyter notebooks on our DeTT&CT GitHub.

**Comment by juliamiyazato** [comment]
Did you manage to solve it? I'm having the same issue over here.

**Comment by neeti306** [comment]
No, I couldn't. However I have created new environment and installed most of the libraries/packages which are present in base package and its working fine.
