### ISSUE TITLE
Problem Writing detection coverage layer with visibility as overlay

### ISSUE THREAD

**Issue by sherlon1** [rabobank-cdc/DeTTECT#38]
Hi,

I'm trying to generate a layer to view in Attack and am encountering the below error:

Writing detection coverage layer with visibility as overlay...
Traceback (most recent call last):
  File "dettect.py", line 366, in <module>
    _menu(_init_menu())
  File "dettect.py", line 239, in _menu
    interactive_menu()
  File "C:\Users\test\Desktop\Dettect_new\interactive_menu.py", line 79, in interactive_menu
    _menu_detection(_select_file(MENU_NAME_DETECTION_COVERAGE_MAPPING, 'techniques', FILE_TYPE_TECHNIQUE_ADMINISTRATION))
  File "C:\Users\test\Desktop\Dettect_new\interactive_menu.py", line 362, in _menu_detection
    generate_detection_layer(file_tech, filename_ds, True, None, None)
  File "C:\Users\test\Desktop\Dettect_new\technique_mapping.py", line 30, in generate_detection_layer
    mapped_techniques_both = _map_and_colorize_techniques_for_overlaid(my_techniques, my_data_sources, platform)
  File "C:\Users\test\Desktop\Dettect_new\technique_mapping.py", line 341, in _map_and_colorize_techniques_for_overlaid
    x['metadata'].append({'name': 'ATT&CK data sources', 'value': ', '.join(get_applicable_data_sources_technique(technique['x_mitre_data_sources'],
  File "C:\Python38\lib\site-packages\stix2\base.py", line 216, in __getitem__
    return self._inner[key]
KeyError: 'x_mitre_data_sources'

Can you please advise on what I'm doing wrong? Apologies if it's something obvious :) 

Thanks,
Sherlon

**Comment by marcusbakker** [comment]
Hi @sherlon1,

Thanks for reporting this bug!

I pushed a fix. Could you try again with the latest version from GitHub to see if this resolves the bug?

Regards,
Marcus

**Comment by sherlon1** [comment]
Hi @marcusbakker 

Thanks for the quick response. I can confirm that the fix works!

Thanks for all the work on this project and keep up the good work!

Cheers,
Sherlon

**Comment by marcusbakker** [comment]
Hi @sherlon1,

Good to hear this fixes the issue. Thanks! 😄 

Regards,
Marcus
