### ISSUE TITLE
Feature request - Non-zero exits codes DeTT&CT CLI

### ISSUE THREAD

**Issue by SanWieb** [rabobank-cdc/DeTTECT#46]
Hi!

I would like to automate the generation of ATT&CK Layers with DeTT&CT via GIT actions. Detecting if the generation succeeds would be much easier if the DeTT&CT CLI exits with a non-zero code after failure. 
Especially for the health check of the yaml files, but also for example when a yaml does not exists.

Is this an idea or was it a deliberate choice to have only zero exit codes?

Alternative is to check the output of the DeTT&CT CLI with a second script and base the exit code on the output, however this would be not very easy and clean.

**Comment by arashnikoo** [comment]
I have the same problem. I haven't been able to get the YAML convert.

**Comment by rubinatorz** [comment]
Hi @SanWieb 

Thank you for this input! We have something related to this on our backlog and I've incorporated your request to that. Right now it has a low priority given other items that we are working on.

Regards,
Ruben

**Comment by rubinatorz** [comment]
Hi @arashnikoo 

Do you still have issues with that YAML? When using latest DeTT&CT version with all the packages from requirements.txt and using python 3.8, I don't get any error based on your given YAML file.

Regards,
Ruben

**Comment by cpaul82** [comment]
Hi @rubinatorz 

I have the latest DeTT&CT, all the packages from requirements.txt are the latest, and using the python 3.8, still unable to convert the given YAML to file json.

Traceback (most recent call last):
  File "dettect.py", line 365, in <module>
    _menu(_init_menu())
  File "dettect.py", line 254, in _menu
    generate_data_sources_layer(file_ds, args.output_filename, args.layer_name, args.platform)
  File "/root/DeTTECT/data_source_mapping.py", line 24, in generate_data_sources_layer
    my_techniques = _map_and_colorize_techniques(my_data_sources, platform, exceptions)
  File "/root/DeTTECT/data_source_mapping.py", line 261, in _map_and_colorize_techniques
    total_ds_count = _count_applicable_data_sources(t, applicable_data_sources)
  File "/root/DeTTECT/data_source_mapping.py", line 240, in _count_applicable_data_sources
    ds = ds.split(':')[1][1:]
IndexError: list index out of range

Could you please help?

**Comment by rubinatorz** [comment]
Hi @cpaul82 it seems that both errors are the same. On both code lines the data source from the MITRE data is split based on the colon. In every data source there's a colon to split the data source and data component:

`User Account: User Account Modification`

We case the ATT&CK STIX data in the cache directory, and I think this local cache file is corrupt or outdated. Can you please try to remove the cache folder and try the command again?

**Comment by rubinatorz** [comment]
hi @cpaul82 

We've found the issue ("IndexError: list index out of range"), it is related to the newest version of the attackcti library. Please use version 0.3.3 as mentioned in the requirements.txt. See also my [comment](https://github.com/rabobank-cdc/DeTTECT/issues/54#issuecomment-868674986) in issue #54.

**Comment by OmegaBodega** [comment]
Hi @rubinatorz I'm having a similar error:
  " if len(subtech['techniqueID']) == 9:                                                                                
TypeError: object of type 'NoneType' has no len()"

I've made sure the packages installed are the same versions listed in requirements.txt, as you mentioned above, but the error persists.

Any help would be appreciated
